import = ["/Users/lucas/.config/alacritty/themes/themes/tokyo-night.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[scrolling]
history = 5000

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 160
lines = 60

[window.padding]
x = 10
y = 10
