require 'user.globals'
require 'user.options'
require 'user.keymaps'
require 'user.colors'
require 'user.plugins'
require 'user.autocmds'
require 'user.diagnostic'
require 'user.plugins.lualine'
require 'user.plugins.cmp'
require 'user.plugins.lsp'
require 'user.plugins.fidget'
require 'user.plugins.treesitter'
-- require 'user.plugins.nvim-tree'
require 'user.plugins.comment'
require 'user.plugins.glow'
require 'user.plugins.telescope'
require 'user.plugins.toggleterm'
require 'user.plugins.mason'
-- require 'user.plugins.bufferline'
require 'user.plugins.autopairs'
require 'user.plugins.flote'
