#+TITLE: Emacs Config
#+AUTHOR: Lucas Sanchez
#+DESCRIPTION: My literal Emacs configuration.
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Table of contents :toc:
- [[#bootstrap][Bootstrap]]
- [[#completions][Completions]]
  - [[#which-key][Which-Key]]
  - [[#vertico][Vertico]]
  - [[#marginalia][Marginalia]]
  - [[#recentf][Recentf]]
  - [[#savehist][Savehist]]
  - [[#orderless][Orderless]]
  - [[#company][Company]]
  - [[#eglot][Eglot]]
- [[#consult][Consult]]
- [[#dashboard][Dashboard]]
- [[#delsel][Delsel]]
- [[#diminish][Diminish]]
- [[#evil-mode][Evil mode]]
- [[#flycheck][Flycheck]]
- [[#functions][Functions]]
- [[#general-keybindings][General keybindings]]
- [[#misc-settings][Misc settings]]
  - [[#macos-keys][macOS keys]]
  - [[#smooth-scrolling][Smooth scrolling]]
  - [[#short-prompts][Short prompts]]
  - [[#font][Font]]
- [[#modeline][Modeline]]
- [[#org][Org]]
  - [[#general-org-settings][General Org Settings]]
  - [[#agenda][Agenda]]
  - [[#org-todo][Org TODO]]
  - [[#org-capture][Org Capture]]
  - [[#toc-org][Toc-Org]]
  - [[#org-tempo][Org-Tempo]]
- [[#packages][Packages]]
- [[#rainbow-mode][Rainbow mode]]
- [[#project][Project]]
- [[#terminals][Terminals]]
  - [[#vterm][Vterm]]
  - [[#vterm-toggle][Vterm-Toggle]]
- [[#themes][Themes]]
- [[#ui][UI]]

* Bootstrap

Separate customizations written by Emacs into its own file so they
don't clutter this config.

#+begin_src emacs-lisp
  (setq custom-file (locate-user-emacs-file "custom.el"))
  (load custom-file 'noerror 'nomessage)
#+end_src

Keep backups in a dedicated directory instead of scattered next to the
original files.

#+begin_src emacs-lisp
  (setq backup-directory-alist '((".*" . "~/.config/emacs/backups/")))
#+end_src

* Completions

** Which-Key

Pops up a panel showing available keybindings when you stall
mid-shortcut.

#+begin_src emacs-lisp
  (use-package which-key
    :init (which-key-mode)
    :diminish
    :config
    (setq which-key-idle-delay 0.3))
#+end_src

** Vertico

#+begin_src emacs-lisp
  (use-package vertico
    :config
    (vertico-mode 1))
#+end_src

** Marginalia

#+begin_src emacs-lisp
  (use-package marginalia
    :config
    (marginalia-mode 1))
#+end_src

** Recentf
#+begin_src emacs-lisp
  (recentf-mode 1)
  (setq recentf-max-saved-items 25)
  (setq tab-always-indent 'complete) ; Optional helpful Vertico setting
  (setq-default read-buffer-completion-ignore-case t)
  (setq-default read-file-name-completion-ignore-case t)
#+end_src

** Savehist

#+begin_src emacs-lisp
    (use-package savehist
      :config
      (savehist-mode 1)
      )
#+end_src

** Orderless

#+begin_src emacs-lisp
  (use-package orderless
    :config
    (setq completion-styles '(orderless basic))
    (setq completion-category-defaults nil))
#+end_src

** Company

A clean, modern inline auto-completion popup menu.

#+begin_src emacs-lisp
  (use-package company
    :defer 2
    :diminish
    :custom
    (company-begin-commands '(self-insert-command))
    (company-idle-delay .1)
    (company-minimum-prefix-length 2)
    (company-show-numbers t)
    (company-tooltip-align-annotations 't)
    (global-company-mode t))

  (use-package company-box
    :after company
    :diminish
    :hook (company-mode . company-box-mode))
#+end_src

** Eglot

#+begin_src emacs-lisp
  (use-package eglot
    :hook ((sh-mode . eglot-ensure)
  	 (python-mode . eglot-ensure)
  	 (python-ts-mode . eglot-ensure)
  	 (rust-mode . eglot-ensure)
  	 (markdown-mode . eglot-ensure)
  	 (markdown-ts-mode . eglot-ensure)
  	 (html-mode . eglot-ensure)
  	 (css-mode . eglot-ensure)
  	 (css-ts-mode . eglot-ensure)
  	 (html-ts-mode . eglot-ensure)
  	 (js-mode . eglot-ensure)
  	 (js-ts-mode . eglot-ensure)
  	 (typescript-ts-mode . eglot-ensure)
  	 ;;(tsx-ts-mode . eglot-ensure)
  	 (kotlin-ts-mode . eglot-ensure)
  	 (yaml-mode . eglot-ensure)
  	 (yaml-ts-mode . eglot-ensure)
  	 ;; formatting
  	 (before-save . eglot-format-buffer))
    )

  ;;(add-to-list 'auto-mode-alist '("\\.tsx\\'" . tsx-ts-mode))
#+end_src


* Consult
#+begin_src emacs-lisp
    (use-package consult)
#+end_src

* Dashboard
#+begin_src emacs-lisp
  (setq inhibit-startup-screen t)
  (setq initial-scratch-message nil)

  ;; (setq initial-scratch-message 
  ;; 	";; Welcome to Emacs.

  ;; ;; Recent Files:
  ;; ")
#+end_src

* Delsel

#+begin_src emacs-lisp
  (use-package delsel
    :config
    (delete-selection-mode 1))
#+end_src

* Diminish
#+begin_src emacs-lisp
  (use-package diminish)
#+end_src

* Evil mode

#+begin_src emacs-lisp
  (use-package evil
    :config
    (evil-mode 1))

  ;; Using RETURN to follow links in Org/Evil 
  ;; Unmap keys in 'evil-maps if not done, (setq org-return-follows-link t) will not work
  (with-eval-after-load 'evil-maps
    (define-key evil-motion-state-map (kbd "SPC") nil)
    (define-key evil-motion-state-map (kbd "RET") nil)
    (define-key evil-motion-state-map (kbd "TAB") nil))

  ;; Setting RETURN key in org-mode to follow links
  (setq org-return-follows-link  t)
#+end_src

* Flycheck
#+begin_src emacs-lisp
  (use-package flycheck
    :defer t
    :diminish
    :init (global-flycheck-mode))
#+end_src


* Functions

Open the init file from anywhere.

#+begin_src emacs-lisp
  (defun lg/open-init-file ()
    "Open the literal Emacs configuration file config.org."
    (interactive)
    (find-file (expand-file-name "config.org" user-emacs-directory)))

  ;; (global-set-key (kbd "C-c i") #'lg/open-init-file)
#+end_src

* General keybindings

#+begin_src emacs-lisp
  (use-package general
    :config
    (general-evil-setup)

    ;; set up 'SPC' as the global leader key
    (general-create-definer lg/leader-keys
      :states '(normal insert visual emacs)
      :keymaps 'override
      :prefix "SPC" ;; set leader
      :global-prefix "M-SPC") ;; access leader in insert mode

    (lg/leader-keys
      "." '(find-file :wk "Find file"))

    (lg/leader-keys
      "b" '(:ignore t :wk "Bookmarks/Buffers")
      "b b" '(consult-buffer :wk "Switch to buffer")
      "b i" '(ibuffer :wk "Ibuffer")
      "b k" '(kill-buffer :wk "Kill buffer")
      "b K" '(kill-some-buffers :wk "Kill multiple buffers")
      "b l" '(list-bookmarks :wk "List bookmarks")
      "b m" '(bookmark-set :wk "Set bookmark")
      "b n" '(next-buffer :wk "Next buffer")
      "b p" '(previous-buffer :wk "Previous buffer")
      "b r" '(revert-buffer :wk "Revert buffer")
      "b R" '(rename-buffer :wk "Rename buffer")
      "b s" '(basic-save-buffer :wk "Save buffer")
      "b S" '(save-some-buffers :wk "Save multiple buffers")
      "b w" '(bookmark-save :wk "Save current bookmarks to bookmark file")
      )

    (lg/leader-keys
      "c" '(:ignore t :wk "Code (Eglot)")
      "c r" '(eglot-rename :wk "Rename")
      "c a" '(eglot-code-actions :wk "Code Actions")
      "c f" '(eglot-format-buffer :wk "Format Buffer")
      "c i" '(eglot-find-implementation :wk "Find implementation"))

    (lg/leader-keys
      "d" '(:ignore t :wk "Dired")
      "d d" '(dired :wk "Open dired")
      "d j" '(dired-jump :wk "Dired jump to current"))

    (lg/leader-keys
      "e" '(:ignore t :wk "Ediff/Eshell/Eval/EWW")
      "e b" '(eval-buffer :wk "Evaluate elisp in buffer")
      "e d" '(eval-defun :wk "Evaluate defun containing or after point")
      "e e" '(eval-expression :wk "Evaluate and elisp expression")
      "e f" '(ediff-files :wk "Run ediff on a pair of files")
      "e F" '(ediff-files3 :wk "Run ediff on three files")
      "e l" '(eval-last-sexp :wk "Evaluate elisp expression before point")
      "e n" '(eshell-new :wk "Create new eshell buffer")
      "e r" '(eval-region :wk "Evaluate elisp in region")
      "e R" '(eww-reload :which-key "Reload current page in EWW")
      "e s" '(eshell :which-key "Eshell")
      "e w" '(eww :which-key "EWW emacs web wowser"))

    (lg/leader-keys
      "f" '(:ignore t :wk "Files")
      "f c" '((lambda () (interactive)
                (lg/open-init-file))
              :wk "Open config.org")
      "f g" '(consult-grep :wk "Search for string current file")
      "f l" '(consult-locate :wk "Locate a file")
      "f r" '(consult-recent-file :wk "Find recent files")
      "f s" '(consult-line :wk "Search for a match line")
      )

    (lg/leader-keys
      "h" '(:ignore t :wk "Help")
      "h c" '(describe-command :w "Describe command")
      "h f" '(describe-function :w "Describe function")
      "h F" '(describe-face :w "Describe face")
      "h m" '(describe-mode :w "Describe mode")
      "h v" '(describe-variable :wk "Describe variable")
      "h r" '(lambda () (interactive) (load-file user-init-file) :wk "Reload Emacs config")
      )

    (lg/leader-keys
      "o" '(:ignore t :wk "Org")
      "o a" '(org-agenda :wk "Org agenda")
      "o c" '(org-capture :wk "Org capture")
      "o f" '(make-frame :wk "Open buffer in new frame")
      "o F" '(select-frame-by-name :wk "Select frame by name")
      "o i" '((lambda () (interactive) (find-file org-default-notes-file)) :wk "Inbox")
      "o j" '((lambda () (interactive) (find-file (concat org-directory "journal.org"))) :wk "Journal")
    )

  (lg/leader-keys
    "t" '(:ignore t :wk "Terminal")
    "t v" '(vterm-toggle :wk "Toggle vterm"))

  (lg/leader-keys
    "w" '(:ignore t :wk "Windows/Words")
    ;; Window splits
    "w c" '(evil-window-delete :wk "Close window")
    "w n" '(evil-window-new :wk "New window")
    "w s" '(evil-window-split :wk "Horizontal split window")
    "w v" '(evil-window-vsplit :wk "Vertical split window")
    ;; Window motions
    "w h" '(evil-window-left :wk "Window left")
    "w j" '(evil-window-down :wk "Window down")
    "w k" '(evil-window-up :wk "Window up")
    "w l" '(evil-window-right :wk "Window right")
    "w w" '(evil-window-next :wk "Goto next window")
    ;; Move Windows
    "w H" '(buf-move-left :wk "Buffer move left")
    "w J" '(buf-move-down :wk "Buffer move down")
    "w K" '(buf-move-up :wk "Buffer move up")
    "w L" '(buf-move-right :wk "Buffer move right")
    ;; Words
    "w d" '(downcase-word :wk "Downcase word")
    "w u" '(upcase-word :wk "Upcase word")
    "w =" '(count-words :wk "Count words/lines for buffer"))
  )
#+end_src

* Misc settings

#+begin_src emacs-lisp
  (setq inhibit-startup-message t) ; Lose the default welcome screen
  (setq visible-bell nil)
  (setq mouse-drag-copy-region t)
  (setq bookmark-save-flag 1)

  ;; Automatically reload buffers when files change on disk (e.g. via iCloud sync)
  (global-auto-revert-mode 1)

  ;; Silence the "Reverting buffer..." messages in the echo area to avoid clutter
  (setq auto-revert-verbose nil)
#+end_src

** macOS keys

By default, Cmd is =meta= and Option stays free for typing symbols.
Commented out since the defaults already work.

#+begin_src emacs-lisp 
  ;; (setq mac-command-modifier 'meta)       ; Cmd acts as Meta (Alt)
  ;; (setq mac-option-modifier 'none)        ; Opt stays normal for typing symbols like Option+7
  ;; (setq ordinary-keyboard-patch t)
#+end_src

** Smooth scrolling

Stop Emacs from jumping half a page on long scrolls.

#+begin_src emacs-lisp
  (setq scroll-conservatively 101)
  (setq mouse-wheel-scroll-amount '(1 ((shift) . 1)))
  (setq mouse-wheel-progressive-speed nil)
#+end_src

** Short prompts

Make "yes or no" prompts just "y or n".

#+begin_src emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+end_src

** Font

#+begin_src emacs-lisp
  ;;(set-face-attribute 'default nil :family "Hack Nerd Font" :height 150 :foreground 'unspecified)
  ;;(set-face-attribute 'default nil :family "JetBrains Mono" :height 140)
  (set-face-attribute 'default nil :family "Iosevka Nerd Font Mono" :height 160)
  ;;(set-face-attribute 'default nil :family "IosevkaTerm Nerd Font Mono" :height 160)
  ;;(set-face-attribute 'default nil :family "FiraMono Nerd Font Mono" :height 140 :weight 'medium)
  ;;(set-face-attribute 'default nil :family "Monolisa" :height 130)
#+end_src

* Modeline
#+begin_src emacs-lisp
(use-package doom-modeline
    :init (doom-modeline-mode 1))
#+end_src

* Org

** General Org Settings
#+begin_src emacs-lisp
    ;; iCloud synced folder
    ;;(setq org-directory "~/Library/Mobile Documents/com~apple~CloudDocs/Org/")
    (setq org-directory "~/Org/")
#+end_src

** Agenda
#+begin_src emacs-lisp
  (setq org-agenda-files 
	(list (concat org-directory "inbox.org")
	      (concat org-directory "journal.org")))
#+end_src

** Org TODO
#+begin_src emacs-lisp
  (setq org-todo-keywords
        '((sequence "TODO(t)" "INPROGRESS(p)" "|" "DONE(d)" "WONTDO(w)")))
#+end_src

** Org Capture
#+begin_src emacs-lisp
  ;; Defines the global fallback destination for all your Org notes.
  (setq org-default-notes-file (concat org-directory "inbox.org"))

  (setq org-capture-templates
        `(

  	("t" "Todo" entry (file+headline org-default-notes-file "Tasks")
  	 "* TODO %?\n  %i\n  %a")

  	("n" "Note" entry (file+headline org-default-notes-file "Notes")
  	 "* %?\n  Entered on %U")

  	("j" "Journal" entry
  	 (file+datetree (concat org-directory "journal.org"))
  	 "* %?\n  Entered on %U")

        ))
#+end_src

** Toc-Org
#+begin_src emacs-lisp
  (use-package toc-org
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-mode))
#+end_src


** Org-Tempo

| Typing the below + TAB | Expands to ...                          |
|------------------------+-----------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |

#+begin_src emacs-lisp
  (require 'org-tempo)
#+end_src

* Packages

Initialize package repositories.

#+begin_src emacs-lisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
#+end_src

Initialize =use-package= (built into Emacs 29+). This ensures packages
are automatically installed if they aren't on your system.

#+begin_src emacs-lisp
  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :if (memq window-system '(mac ns))
    :config
    (exec-path-from-shell-initialize))
#+end_src

* Rainbow mode
#+begin_src emacs-lisp
  (use-package rainbow-mode
    :diminish
    :hook org-mode prog-mode)
#+end_src

* Project
#+begin_src emacs-lisp
  (use-package project
    :custom
    (project-list-file "~/.config/emacs/.emacs-projects-list")
    (project-mode-line t)
    (project-kill-buffers-display-buffer-list t))
#+end_src

* Terminals

** Vterm

#+begin_src emacs-lisp
  (use-package vterm
    :config
    (setq shell-file-name "/bin/sh"
          vterm-max-scrollback 5000))

  (add-hook 'vterm-mode-hook (lambda () (display-line-numbers-mode -1)))

#+end_src

** Vterm-Toggle
#+begin_src emacs-lisp
    (use-package vterm-toggle
      :after vterm
      :config
      ;; When running programs in Vterm and in 'normal' mode, make sure that ESC
      ;; kills the program as it would in most standard terminal programs.
      (evil-define-key 'normal vterm-mode-map (kbd "<escape>") 'vterm--self-insert)
      (setq vterm-toggle-fullscreen-p nil)
      (setq vterm-toggle-scope 'project))

    (with-eval-after-load 'vterm
      (add-to-list 'display-buffer-alist
                   '((lambda (buffer-or-name _)
                       (let ((buffer (get-buffer buffer-or-name)))
                         (with-current-buffer buffer
                           (or (equal major-mode 'vterm-mode)
                               (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                     (display-buffer-reuse-window display-buffer-in-side-window)
                     (side . bottom)
                     (reusable-frames . visible)
                     (window-width . 0.4))))
#+end_src


* Themes

#+begin_src emacs-lisp
  ;; (load-theme 'modus-operandi)
  ;; (load-theme 'modus-vivendi)
  ;; (load-theme 'modus-vivendi-tinted)

  ;; (use-package kanagawa-themes
  ;;   :config
  ;;   (load-theme 'kanagawa-wave t))

  (use-package doom-themes
    :custom
    ;; Global settings (defaults)
    (doom-themes-enable-bold t)   ; if nil, bold is universally disabled
    (doom-themes-enable-italic t) ; if nil, italics is universally disabled
    :config
    ;;(load-theme 'doom-one t)
    (load-theme 'doom-tomorrow-night t)

    ;; Enable flashing mode-line on errors
    (doom-themes-visual-bell-config)
    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config))

  ;; (add-to-list 'custom-theme-load-path "~/.config/emacs/themes/")
  ;; (add-hook 'emacs-startup-hook (lambda () (load-theme 'dtmacs t)))
#+end_src

* UI

Strip away the chrome we don't need. *Moved to early-init.el*

#+begin_src emacs-lisp
  ;; (scroll-bar-mode -1)             ; Disable ugly scrollbars
  ;; (tool-bar-mode -1)               ; Disable the graphical toolbar
  ;; (tooltip-mode -1)                ; Disable tooltips
  ;; (set-fringe-mode 10)             ; Give some breathing room on the sides
  ;; (menu-bar-mode -1)               ; Disable the menu bar
#+end_src

Show line numbers and the current column in the modeline.

#+begin_src emacs-lisp
  (global-display-line-numbers-mode t) ; Show line numbers
  (column-number-mode t)                ; Show column number in the modeline
  ;;(setq org-edit-src-content-indentation 0) ;; Set src block automatic indent to 0 instead of 2.
  (setq use-file-dialog nil)   ;; No file dialog
  (setq use-dialog-box nil)    ;; No dialog box
  (setq pop-up-windows nil)    ;; No popup windows
#+end_src

Disable line numbers for modes where they don't make sense.

#+begin_src emacs-lisp
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src
