local options = {
  backup = false,
  clipboard = "unnamedplus",
  completeopt = "menuone,noselect,noinsert",
  cursorline = true,
  fileencoding = 'utf-8',
  guifont = "monospace:h14",
  hlsearch = true,
  hidden = true,
  ignorecase = true,
  incsearch = true,
  expandtab = true,
  laststatus = 3,
  mouse = "a",
  number = true,
  pumheight = 10,
  relativenumber = false,
  scrolloff = 8,
  showmode = false,
  shiftwidth = 2,
  sidescrolloff = 8,
  smartcase = true,
  smartindent = true,
  softtabstop = 2,
  splitbelow = true,
  splitright = true,
  swapfile = false,
  termguicolors = true,
  tabstop = 2,
  wildmenu = true,
  wrap = true,
}

for k, v in pairs(options) do
  vim.opt[k] = v
end
