#term xterm-kitty
term xterm-256color

# font_family      JetBrainsMono Nerd Font Mono
font_family      Hack 
bold_font        auto
bold_italic_font auto
italic_font      auto
# italic_font Cartograph CF Italic

font_size 14
background_opacity 1

disable_ligatures never

# Nerd Fonts v2.3.3
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono

# The default is ctrl+shift 
kitty_mod cmd+option

# no sound 
enable_audio_bell no

# cursor
shell_integration no-cursor
# cursor_shape block
cursor_blink_interval 0 
cursor_stop_blinking_after 0 

# cursor_shape beam
# cursor_beam_thickness 1.5
# cursor_underline_thickness 2.0
# cursor_blink_interval 0
# cursor_stop_blinking_after 0
# cursor_trail 1
# cursor_trail_decay 0.01 0.5
# cursor_trail_start_threshold 0

copy_on_select yes

# os
macos_option_as_alt yes
macos_quit_when_last_window_closed yes

# tab bar
tab_bar_style powerline
tab_powerline_style angled
focus_follows_mouse     yes
tab_title_template      {index}: {title}
active_tab_foreground   #000
active_tab_background   #eee
active_tab_font_style   bold-italic
inactive_tab_foreground #444
inactive_tab_background #999
inactive_tab_font_style normal

# window 
remember_window_size  yes
initial_window_width  640
initial_window_height 400
# hide_window_decorations yes
window_border_width 4 
window_margin_width 4
# draw_minimal_borders yes

# Move between tabs
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7

map ctrl+b>1 goto_tab 1
map ctrl+b>2 goto_tab 2
map ctrl+b>3 goto_tab 3
map ctrl+b>4 goto_tab 4
map ctrl+b>5 goto_tab 5
map ctrl+b>6 goto_tab 6
map ctrl+b>7 goto_tab 7

# Full screen
map f5 toggle_fullscreen

# specific layouts
map ctrl+b>u goto_layout tall
map ctrl+b>i goto_layout fat
map ctrl+b>o goto_layout stack

# window navigation
map cmd+enter new_window
# map ctrl+l next_window
# map ctrl+h previous_window

map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+j neighboring_window bottom
map ctrl+k neighboring_window up

# sessions
map ctrl+b>n goto_session $HOME/.config/kitty/sessions/notes.kitty-session
map ctrl+b>w goto_session $HOME/.config/kitty/sessions/work.kitty-session

# Browse and select from the list of known projects defined via goto_session commands
map ctrl+b>s goto_session

# reload config
map ctrl+b>r load_config_file

# include gruvbox_dark.conf
# include SpaceGray.conf
# include ayu_mirage.conf

include current-theme.conf
